### ISSUE TITLE
invalid syntax : what do I have to do ?

### ISSUE THREAD

**Issue by npettiaux** [SkullCarverCoder/wc18-cli#3]
wc18 --country=belgium
Traceback (most recent call last):
  File "./.local/bin/wc18", line 7, in <module>
    from wc18.wc18 import main
  File "/home/npx/.local/lib/python2.7/site-packages/wc18/wc18.py", line 234
    click.echo('TEAM: ' + click.style(f'{team.Nation}', fg="magenta", bold=True))
                                                     ^
SyntaxError: invalid syntax

**Comment by SkullCarverCoder** [comment]
What type of installation did you do? I tried to replicate your error but I got just a invalid country error given that the names of the nations must be capitalized on the first letter i.e : "Belgium". Try updating if you did pip install !

**Comment by SkullCarverCoder** [comment]
Due to no answer this issue is closed
